services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./app/server
    env_file:
      - ./server/.env
  web:
    build: ./web
    container_name: caddy_server
    ports:
      - "5173:80"
    volumes:
      - ./web:/app:ro